Added logging in program.cs
bluefire0009/Project-Process-and-Tools-v2 pull request #50
Opened 2024-12-09 10:19 UTC by JohnSpruijt2

2024-12-10 10:46 UTC, bluefire0009 requested changes
Add in 2 places logging for transfers, same as in version 1, you can find them by using ctrl+shift+f and typing in "push("

2024-12-10 13:06 UTC, bluefire0009 requested changes
Also when logging of all requests, the body of the request should be logged as well. It can be done like this:

```
app.Use(async (context, next) =>
            {
                // Ensure the request body can be read multiple times (e.g., for logging or processing).
                context.Request.EnableBuffering();
                using (var reader = new StreamReader(
                context.Request.Body,
                encoding: Encoding.UTF8,
                detectEncodingFromByteOrderMarks: false,
                bufferSize: 1024,
                leaveOpen: true))
                {
                    string body = await reader.ReadToEndAsync();

                    // Reset the stream position to allow subsequent reads by the framework or other middleware.
                    context.Request.Body.Position = 0;
                    await System.IO.File.AppendAllTextAsync("log.txt", $"{context.Request.Path} - {body} - {context.Response.StatusCode} \n");
                }


                await next.Invoke();
            });
```

2024-12-10 13:44 UTC, TurboGreaser approved these changes

2024-12-13 21:40 UTC, bluefire0009 approved these changes

2024-12-17 08:01 UTC, merged